// 场景包：AI 产业 · 框架之战（模型之争 → 执行框架/工具链/生态之争的行业动态推演）
export default {
  id: 'ai',
  label: 'AI 产业 · 框架之战',
  domain: 'AI 行业竞争',
  entityTypes: ['模型厂商', '开源社区', '开发者生态', '云厂商', '企业客户', '监管机构', '投资人', '算力供应商', '执行框架', '模型', '工具链', '评测基准'],
  typeColor: {
    '模型厂商': '#0E62C4', '开源社区': '#4CAF50', '开发者生态': '#00BCD4', '云厂商': '#FF9800',
    '企业客户': '#E91E63', '监管机构': '#795548', '投资人': '#FFC107', '算力供应商': '#009688',
    '执行框架': '#FF5722', '模型': '#455A64', '工具链': '#607D8B', '评测基准': '#8BC34A',
  },
  personKeywords: ['厂', '商', '社区', '生态', '开发', '云', '客户', '机构', '投资', '算力', '家', '者', '司'],
  personTypes: ['模型厂商', '开源社区', '开发者生态', '云厂商', '企业客户', '监管机构', '投资人', '算力供应商'],
  objectTypes: ['执行框架', '模型', '工具链', '评测基准'],
  kpiSchema: ['框架采用率', '开源活跃度', '生态工具数', '推理成本', '开发者满意度', '商业化收入'],
  seedExamples: [
    'OpenAI 与 DeepSeek 同月开源 Harness 框架，开发者生态将如何分化？',
    '若开源框架成为事实标准，闭源模型厂商的护城河还剩什么？',
    '框架之战白热化，云厂商与算力供应商会各自站队哪边？',
    '监管介入 Agent 执行框架，开源生态会否被遏制？',
  ],
  defaultParams: { entN: 12, rounds: 8, perR: 6 },
  demoData: {
    entities: [
      { id: 'openai', name: 'OpenAI', type: '模型厂商', persona: '闭源模型 + 开源框架双线作战', goal: '主导 Agent 执行标准', age: null, gender: '未知', mbti: 'ENTJ', bio: '前沿闭源模型 + 同月开源 Harness', traits: ['强势', '标准野心'], preferences: ['生态绑定'] },
      { id: 'deepseek', name: 'DeepSeek', type: '模型厂商', persona: '全链路开源、极致性价比', goal: '以开源生态反超', age: null, gender: '未知', mbti: 'INTJ', bio: '模型 + 框架全开源，成本优势明显', traits: ['激进开源', '成本领先'], preferences: ['社区共建'] },
      { id: 'anthropic', name: 'Anthropic', type: '模型厂商', persona: '安全优先、企业向', goal: '守住高端开发者', age: null, gender: '未知', mbti: 'INFJ', bio: '强调安全与可解释', traits: ['安全导向'], preferences: ['企业定制'] },
      { id: 'google', name: 'Google Cloud', type: '云厂商', persona: '模型中立、卖云服务', goal: '托管与算力收入', age: null, gender: '未知', mbti: 'ESTJ', bio: '多模型 + 托管平台', traits: ['中立', '渠道广'], preferences: ['托管服务'] },
      { id: 'community', name: '开源社区', type: '开源社区', persona: '共建与分叉', goal: '自由与影响力', age: null, gender: '未知', mbti: 'ENFP', bio: '围绕框架形成技术共同体', traits: ['活跃', '分叉倾向'], preferences: ['开放协议'] },
      { id: 'devs', name: '开发者生态', type: '开发者生态', persona: '用脚投票', goal: '效率与低迁移成本', age: 30, gender: '未知', mbti: 'INTP', bio: '工具链与 Agent 应用的实际建设者', traits: ['务实', '易迁移'], preferences: ['顺手', '文档好'] },
      { id: 'ent', name: '企业客户', type: '企业客户', persona: '稳定与成本并重', goal: '可落地的 AI 应用', age: null, gender: '未知', mbti: 'ISTJ', bio: '关注 ROI 与供应商锁定风险', traits: ['谨慎', '成本敏感'], preferences: ['私有化', 'SLA'] },
      { id: 'reg', name: '监管机构', type: '监管机构', persona: '安全与责任', goal: '风险可控', age: null, gender: '未知', mbti: 'ISFJ', bio: '对 Agent 自主行动提出合规要求', traits: ['审慎', '滞后'], preferences: ['备案', '审计'] },
      { id: 'vc', name: '风险投资', type: '投资人', persona: '押注赢家', goal: '生态卡位', age: null, gender: '未知', mbti: 'ENTP', bio: '跟随框架生态下注', traits: ['逐利', '抱团'], preferences: ['热门赛道'] },
      { id: 'nvda', name: '算力供应商', type: '算力供应商', persona: '卖铲人', goal: '算力绑定生态', age: null, gender: '未知', mbti: 'ESTP', bio: '芯片 + 推理基础设施', traits: ['垄断', '绑定'], preferences: ['CUDA 生态'] },
      { id: 'harness_o', name: 'OpenAI Harness', type: '执行框架', persona: '—', goal: '—', specs: 'Agent 执行框架（开源）', impact: '绑定 OpenAI 模型调用', trend: '快速迭代', lifecycle: '持续' },
      { id: 'harness_d', name: 'DeepSeek Harness', type: '执行框架', persona: '—', goal: '—', specs: 'Agent 执行框架（开源）', impact: '模型无关、成本低', trend: '社区增长', lifecycle: '持续' },
      { id: 'toolchain', name: '工具链生态', type: '工具链', persona: '—', goal: '—', specs: 'MCP/插件/编排器', impact: '决定框架粘性', trend: '爆发', lifecycle: '持续' },
      { id: 'pricing', name: '推理定价', type: '模型', persona: '—', goal: '—', specs: 'API token 价格', impact: '左右采用率', trend: '下行', lifecycle: '持续' },
      { id: 'eval', name: 'Agent 评测基准', type: '评测基准', persona: '—', goal: '—', specs: '任务完成率/可靠性', impact: '定义"更强"', trend: '标准化', lifecycle: '季度更新' },
    ],
    edges: [
      ['openai', 'harness_o', '开源发布', 0],
      ['deepseek', 'harness_d', '开源发布', 0],
      ['openai', 'deepseek', '直接竞争', 0],
      ['harness_o', 'devs', '吸引开发者', 0],
      ['harness_d', 'community', '社区共建', 0],
      ['community', 'harness_d', 'Fork 分支', 0],
      ['devs', 'toolchain', '构建工具链', 0],
      ['google', 'harness_o', '托管集成', 0],
      ['google', 'nvda', '算力采购', 0],
      ['ent', 'pricing', '成本敏感', 0],
      ['ent', 'devs', '采购决策', 0],
      ['reg', 'harness_o', '安全审查', 0],
      ['vc', 'openai', '融资加码', 0],
      ['vc', 'deepseek', '估值博弈', 0],
      ['nvda', 'google', '芯片绑定', 0],
      ['eval', 'devs', '选型基准', 0],
      ['anthropic', 'devs', '差异化竞争', 0],
    ],
  },
};
