// 场景包：宏观 · 经济推演（通用宏观经济系统：政策主体 × 经济指标 × 外部冲击）
export default {
  id: 'macro',
  label: '宏观 · 经济推演',
  domain: '宏观经济',
  entityTypes: ['央行', '财政部', '地方政府', '金融机构', '投资者', '企业', '消费者', '国际组织', '政策工具', '经济指标', '外部事件', '资产价格'],
  typeColor: {
    '央行': '#0E62C4', '财政部': '#0088CC', '地方政府': '#4CAF50', '金融机构': '#00BCD4',
    '投资者': '#607D8B', '企业': '#FF9800', '消费者': '#E91E63', '国际组织': '#795548',
    '政策工具': '#FF5722', '经济指标': '#455A64', '外部事件': '#FFC107', '资产价格': '#009688',
  },
  personKeywords: ['行', '部', '委', '局', '府', '企', '家', '者', '员', '长', '司', '会', '组织', '机构'],
  personTypes: ['央行', '财政部', '地方政府', '金融机构', '投资者', '企业', '消费者', '国际组织'],
  objectTypes: ['政策工具', '经济指标', '外部事件', '资产价格'],
  kpiSchema: ['GDP增速', '通胀率', '失业率', '汇率', '利率', '消费信心'],
  seedExamples: [
    '美联储意外降息50bp，人民币汇率与出口如何演变？',
    '新能源产业政策加码，制造业投资能否对冲地产下行？',
    '全球供应链重构，通胀中枢是否永久上移？',
    '人口负增长加速，消费结构将怎样分化？',
  ],
  defaultParams: { entN: 12, rounds: 8, perR: 6 },
  demoData: {
    entities: [
      { id: 'cb', name: '央行', type: '央行', persona: '稳字当头、相机抉择', goal: '稳增长与物价平衡', age: null, gender: '未知', mbti: 'INTJ', bio: '货币政策制定者，重视预期管理', traits: ['审慎', '前瞻'], preferences: ['逆周期调节', '预期管理'] },
      { id: 'treasury', name: '财政部', type: '财政部', persona: '逆周期发力', goal: '稳增长与债务平衡', age: null, gender: '未知', mbti: 'ENTJ', bio: '财政政策主导者', traits: ['积极', '控风险'], preferences: ['专项债', '减税降费'] },
      { id: 'localgov', name: '地方政府', type: '地方政府', persona: '化债与招商并重', goal: '债务化解与稳投资', age: null, gender: '未知', mbti: 'ISTJ', bio: '土地财政承压，转向化债', traits: ['求稳', '杠杆敏感'], preferences: ['专项债项目'] },
      { id: 'bank', name: '商业银行', type: '金融机构', persona: '风险定价、顺周期', goal: '净息差与资产质量', age: null, gender: '未知', mbti: 'ESTJ', bio: '信贷投放主渠道', traits: ['避险', '顺周期'], preferences: ['优质信贷'] },
      { id: 'investor', name: '机构投资者', type: '投资者', persona: '逐利避险', goal: '超额收益', age: null, gender: '未知', mbti: 'ENTP', bio: '股债双配，风险偏好波动大', traits: ['灵活', '敏感'], preferences: ['长久期资产'] },
      { id: 'manufacturer', name: '制造企业', type: '企业', persona: '订单为王', goal: '利润与现金流', age: null, gender: '未知', mbti: 'ENTJ', bio: '出口+内销双轮驱动', traits: ['扩产谨慎'], preferences: ['降本', '融资'] },
      { id: 'household', name: '城镇居民', type: '消费者', persona: '预期偏弱、储蓄意愿高', goal: '收入与安全', age: 35, gender: '未知', mbti: 'ISFJ', bio: '边际消费倾向下降', traits: ['谨慎', '储蓄'], preferences: ['性价比'] },
      { id: 'imf', name: '国际货币基金组织', type: '国际组织', persona: '外部监督与预警', goal: '全球金融稳定', age: null, gender: '未知', mbti: 'INTJ', bio: '发布经济展望与风险评估', traits: ['客观', '权威'], preferences: ['数据监测'] },
      { id: 'policy_rate', name: '政策利率', type: '经济指标', persona: '—', goal: '反映货币取向', specs: '央行7天逆回购利率', impact: '牵引全市场资金成本', trend: '下行通道', lifecycle: '持续' },
      { id: 'cny', name: '人民币汇率', type: '经济指标', persona: '—', goal: '—', specs: 'USD/CNY', impact: '影响出口与资本流动', trend: '双向波动', lifecycle: '持续' },
      { id: 'gdp', name: 'GDP增速', type: '经济指标', persona: '—', goal: '—', specs: '同比增速', impact: '衡量总需求强弱', trend: '承压', lifecycle: '季度' },
      { id: 'subsidy', name: '产业补贴政策', type: '政策工具', persona: '—', goal: '定向支持', specs: '新能源等重点领域', impact: '引导资本与产能', trend: '加码', lifecycle: '3-5年' },
      { id: 'tradewar', name: '贸易摩擦升级', type: '外部事件', persona: '—', goal: '—', specs: '关税+出口管制', impact: '冲击出口链', trend: '升级', lifecycle: '不确定' },
      { id: 'oil', name: '大宗商品价格', type: '资产价格', persona: '—', goal: '—', specs: '能源/金属', impact: '输入性通胀', trend: '高位', lifecycle: '波动' },
    ],
    edges: [
      ['cb', 'policy_rate', '设定利率', 0],
      ['cb', 'cny', '汇率干预', 0],
      ['cb', 'gdp', '稳增长目标', 0],
      ['treasury', 'subsidy', '财政发力', 0],
      ['localgov', 'subsidy', '项目落地', 0],
      ['localgov', 'manufacturer', '招商订单', 0],
      ['bank', 'policy_rate', '跟随定价', 0],
      ['bank', 'investor', '资金融通', 0],
      ['investor', 'cny', '资本流动', 0],
      ['manufacturer', 'household', '就业收入', 0],
      ['household', 'manufacturer', '消费需求', 0],
      ['manufacturer', 'oil', '成本冲击', 0],
      ['tradewar', 'manufacturer', '出口承压', 0],
      ['imf', 'treasury', '外部评估', 0],
      ['cny', 'manufacturer', '汇兑影响', 0],
    ],
  },
};
